#include <mono/jit/jit.h>
#include <mono/metadata/mono-config.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/exception.h>
#include <mono/metadata/mono-gc.h>
#include <mono/metadata/class.h>
#include <mono/metadata/profiler.h>
#include <mono/metadata/mono-debug.h>
#include <mono/metadata/class.h>
#include <mono/metadata/attrdefs.h>